# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagnumber', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['tagnumber'],
            },
        ),
        migrations.CreateModel(
            name='Devtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('i', 'Input Element'), ('o', 'Output Element')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=50)),
                ('plant', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['unit'],
            },
        ),
        migrations.CreateModel(
            name='TestInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular device test', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('o', 'Overdue'), ('s', 'Scheduled')], default='s', max_length=1)),
                ('compliance', models.CharField(blank=True, choices=[('P', 'Passed'), ('f', 'Failed')], max_length=1)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.Device')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='devicetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.Devtype'),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.Location'),
        ),
    ]
