# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devtype',
            new_name='DeviceType',
        ),
    ]
