# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_auto_20170925_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testinstance',
            name='compliance',
        ),
        migrations.AddField(
            model_name='testinstance',
            name='result',
            field=models.CharField(blank=True, choices=[('p', 'Passed'), ('f', 'Failed')], max_length=1),
        ),
        migrations.AddField(
            model_name='testinstance',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testinstance',
            name='tested_by',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
