# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 17:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0005_auto_20170927_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinstance',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
