# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_testinstance_inspector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testinstance',
            options={'ordering': ['due_date'], 'permissions': (('can_mark_approved', 'Mark test as approved'),)},
        ),
        migrations.RemoveField(
            model_name='testinstance',
            name='tested_by',
        ),
    ]
