# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_auto_20170929_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=50)),
                ('doc_name', models.CharField(max_length=50)),
                ('doc_type', models.CharField(blank=True, choices=[('c', 'Cause and Effect'), ('p', 'P&ID'), ('o', 'other')], default='o', max_length=50)),
            ],
            options={
                'ordering': ['doc_number'],
            },
        ),
    ]
