# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0011_auto_20171005_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipl',
            name='ipl_components',
        ),
        migrations.AddField(
            model_name='ipl',
            name='input_elements',
            field=models.ManyToManyField(blank=True, null=True, related_name='_ipl_input_elements_+', related_query_name='IPL input elements', to='inspections.Device'),
        ),
        migrations.AddField(
            model_name='ipl',
            name='output_elements',
            field=models.ManyToManyField(blank=True, null=True, related_name='_ipl_output_elements_+', related_query_name='IPL output elements', to='inspections.Device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='devicetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.DeviceType'),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.Location'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.Location'),
        ),
        migrations.AlterField(
            model_name='ipl',
            name='ipl_doc_references',
            field=models.ManyToManyField(blank=True, null=True, to='inspections.Document', verbose_name='IPL reference documents'),
        ),
    ]
