# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0013_auto_20171005_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipl',
            name='ipl_doc_references',
            field=models.ManyToManyField(blank=True, to='inspections.Document', verbose_name='IPL reference documents'),
        ),
    ]
