# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0014_auto_20171005_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetype',
            options={'ordering': ['category']},
        ),
    ]
