# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0015_auto_20171005_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipl',
            name='ipl_narrative',
            field=models.TextField(blank=True),
        ),
    ]
